import { PrismaClient } from '@prisma/client'
import { randomUUID } from 'crypto'

const prisma = new PrismaClient()

const knowledgeArticles = [
  // ========== COGNITION PILLAR ==========
  {
    title: "The Science of Flow States: How to Access Deep Focus on Demand",
    description: "Understanding the neuroscience behind flow states and practical protocols to trigger them consistently. Learn how dopamine, norepinephrine, and anandamide work together to create peak cognitive performance.",
    pillar: "cognition",
    tags: ["Flow State", "Neuroscience", "Dopamine", "Focus", "Performance"],
    author: "Dr. Andrew Huberman",
    readTime: 12,
    url: "/knowledge/flow-states-neuroscience",
    publishedAt: new Date("2026-01-15"),
  },
  {
    title: "Nootropic Stacks: Evidence-Based Cognitive Enhancement",
    description: "A comprehensive guide to nootropics backed by clinical research, from racetams to natural adaptogens. Includes dosing protocols, synergy combinations, and safety profiles.",
    pillar: "cognition",
    tags: ["Nootropics", "Cognitive Enhancement", "Supplements", "Brain Health"],
    author: "Dr. Rhonda Patrick",
    readTime: 18,
    url: "/knowledge/nootropic-stacks-guide",
    publishedAt: new Date("2026-01-20"),
  },
  {
    title: "Ultradian Rhythms: Optimizing Your 90-Minute Work Cycles",
    description: "How to structure your day around natural 90-minute attention cycles for maximum productivity. Evidence from sleep research applied to waking performance.",
    pillar: "cognition",
    tags: ["Productivity", "Circadian Rhythm", "Focus", "Time Management"],
    author: "Cal Newport",
    readTime: 10,
    url: "/knowledge/ultradian-rhythms",
    publishedAt: new Date("2026-02-01"),
  },
  {
    title: "Neuroplasticity at Any Age: Rewiring Your Brain for Performance",
    description: "How the brain continues to form new neural pathways throughout life. Practical protocols for accelerated learning, skill acquisition, and cognitive resilience using deliberate practice.",
    pillar: "cognition",
    tags: ["Neuroplasticity", "Learning", "Brain Health", "Aging"],
    author: "Dr. Michael Merzenich",
    readTime: 14,
    url: "/knowledge/neuroplasticity-protocols",
    publishedAt: new Date("2026-02-08"),
  },
  {
    title: "The Dopamine System: How to Optimize Motivation Without Burnout",
    description: "Understanding baseline vs. peak dopamine and why the pursuit of constant stimulation leads to depletion. Evidence-based strategies for sustainable motivation and drive.",
    pillar: "cognition",
    tags: ["Dopamine", "Motivation", "Neuroscience", "Mental Health"],
    author: "Dr. Anna Lembke",
    readTime: 13,
    url: "/knowledge/dopamine-optimization",
    publishedAt: new Date("2026-02-12"),
  },
  {
    title: "Speed Reading and Memory Palaces: Ancient Techniques Meet Modern Neuroscience",
    description: "How memory champions achieve extraordinary recall using spatial memory techniques. A step-by-step guide to building your own memory palace and integrating it with modern learning methods.",
    pillar: "cognition",
    tags: ["Memory", "Learning", "Brain Health", "Performance"],
    author: "Jim Kwik",
    readTime: 11,
    url: "/knowledge/memory-techniques",
    publishedAt: new Date("2026-02-16"),
  },
  {
    title: "Omega-3 Fatty Acids and Cognitive Function: The Complete Evidence",
    description: "Systematic review of DHA and EPA's neuroprotective effects. How omega-3 supplementation affects memory, processing speed, and protection against neurodegeneration across the lifespan.",
    pillar: "cognition",
    tags: ["Omega-3", "Brain Health", "Supplements", "Neuroscience"],
    author: "Dr. Rhonda Patrick",
    readTime: 15,
    url: "/knowledge/omega-3-cognitive-function",
    publishedAt: new Date("2026-02-20"),
  },

  // ========== RECOVERY PILLAR ==========
  {
    title: "Sleep Architecture: Mastering the 4 Stages for Optimal Recovery",
    description: "Deep dive into sleep cycles, REM vs deep sleep, and protocols to optimize each stage. How sleep affects memory consolidation, hormonal balance, and immune function.",
    pillar: "recovery",
    tags: ["Sleep", "Recovery", "HRV", "Circadian Rhythm", "Deep Sleep"],
    author: "Dr. Matthew Walker",
    readTime: 15,
    url: "/knowledge/sleep-architecture-guide",
    publishedAt: new Date("2026-01-10"),
  },
  {
    title: "Cold Exposure Protocol: From Beginner to Advanced",
    description: "Science-backed guide to cold showers, ice baths, and deliberate cold exposure for recovery and resilience. Includes temperature ranges, duration protocols, and physiological adaptations.",
    pillar: "recovery",
    tags: ["Cold Therapy", "Recovery", "Dopamine", "Inflammation", "Hormesis"],
    author: "Wim Hof & Dr. Susanna Søberg",
    readTime: 14,
    url: "/knowledge/cold-exposure-protocol",
    publishedAt: new Date("2026-01-25"),
  },
  {
    title: "HRV Tracking: What Your Heart Rate Variability Really Means",
    description: "Understanding HRV metrics, what affects them, and how to use HRV to optimize training and recovery. Includes device recommendations and interpretation frameworks.",
    pillar: "recovery",
    tags: ["HRV", "Recovery", "Stress", "ANS", "Tracking"],
    author: "Dr. Peter Attia",
    readTime: 11,
    url: "/knowledge/hrv-tracking-guide",
    publishedAt: new Date("2026-02-03"),
  },
  {
    title: "Sauna Protocols for Longevity: Heat Shock Proteins and Cardiovascular Health",
    description: "How regular sauna use reduces all-cause mortality by 40%. The science of heat shock proteins, growth hormone release, and cardiovascular conditioning through deliberate heat exposure.",
    pillar: "recovery",
    tags: ["Sauna", "Longevity", "Cardiovascular", "Heat Shock Proteins"],
    author: "Dr. Rhonda Patrick",
    readTime: 13,
    url: "/knowledge/sauna-longevity-protocols",
    publishedAt: new Date("2026-02-07"),
  },
  {
    title: "The Hallmarks of Aging: Understanding Why We Age",
    description: "Exploring the nine hallmarks of aging identified by Lopez-Otin et al. and practical interventions targeting each one — from telomere maintenance to mitochondrial dysfunction.",
    pillar: "recovery",
    tags: ["Longevity", "Aging", "Epigenetics", "Mitochondria", "Cellular Health"],
    author: "David Sinclair",
    readTime: 20,
    url: "/knowledge/hallmarks-of-aging",
    publishedAt: new Date("2026-02-11"),
  },
  {
    title: "Breathwork Protocols: From Box Breathing to Wim Hof Method",
    description: "Comprehensive comparison of breathing techniques and their specific physiological effects. When to use each protocol for stress reduction, performance, or recovery.",
    pillar: "recovery",
    tags: ["Breathwork", "Recovery", "Stress", "Performance", "Cold Therapy"],
    author: "James Nestor",
    readTime: 12,
    url: "/knowledge/breathwork-protocols",
    publishedAt: new Date("2026-02-15"),
  },
  {
    title: "Bryan Johnson's Blueprint: What We Can Learn from the Most Measured Human",
    description: "An analysis of Bryan Johnson's $2M/year age reversal protocol. Which interventions have the strongest evidence, which are experimental, and what regular people can actually implement.",
    pillar: "recovery",
    tags: ["Longevity", "Biohacking", "Aging", "Protocols", "Biomarkers"],
    author: "Dr. Peter Attia",
    readTime: 16,
    url: "/knowledge/bryan-johnson-blueprint-analysis",
    publishedAt: new Date("2026-02-19"),
  },
  {
    title: "NSDR (Non-Sleep Deep Rest): The 20-Minute Recovery Protocol",
    description: "How yoga nidra and NSDR protocols can accelerate recovery, improve learning retention, and replenish dopamine. A practical guide with scripted sessions.",
    pillar: "recovery",
    tags: ["Recovery", "Sleep", "Dopamine", "Meditation", "Neuroplasticity"],
    author: "Dr. Andrew Huberman",
    readTime: 10,
    url: "/knowledge/nsdr-protocol",
    publishedAt: new Date("2026-02-23"),
  },

  // ========== FUELING PILLAR ==========
  {
    title: "Metabolic Flexibility: Training Your Body to Burn Fat and Glucose",
    description: "How to build metabolic flexibility through strategic fasting, ketosis, and carb cycling. Understanding insulin sensitivity and mitochondrial function for optimal energy.",
    pillar: "fueling",
    tags: ["Metabolism", "Ketosis", "Fasting", "Nutrition", "Mitochondria"],
    author: "Dr. Ben Bikman",
    readTime: 16,
    url: "/knowledge/metabolic-flexibility",
    publishedAt: new Date("2026-01-12"),
  },
  {
    title: "Intermittent Fasting Protocols: Finding Your Optimal Window",
    description: "Comparing 16:8, 18:6, OMAD, and alternate-day fasting with practical implementation strategies. How circadian rhythm aligns with eating windows for maximum metabolic benefit.",
    pillar: "fueling",
    tags: ["Fasting", "Autophagy", "Insulin", "Weight Loss", "Longevity"],
    author: "Dr. Jason Fung",
    readTime: 13,
    url: "/knowledge/intermittent-fasting-protocols",
    publishedAt: new Date("2026-01-18"),
  },
  {
    title: "Protein Timing and Muscle Protein Synthesis",
    description: "Evidence-based guide to protein intake timing, amounts, and sources for optimal body composition. The leucine threshold, anabolic window, and protein distribution across meals.",
    pillar: "fueling",
    tags: ["Protein", "Nutrition", "Muscle", "Recovery", "MPS"],
    author: "Dr. Layne Norton",
    readTime: 12,
    url: "/knowledge/protein-timing-guide",
    publishedAt: new Date("2026-02-05"),
  },
  {
    title: "The Gut-Brain Axis: How Your Microbiome Controls Your Mood",
    description: "How gut bacteria communicate with the brain through the vagus nerve and produce neurotransmitters. Practical dietary strategies to optimize your microbiome for mental health.",
    pillar: "fueling",
    tags: ["Gut Health", "Microbiome", "Brain Health", "Neuroscience", "Nutrition"],
    author: "Dr. Emeran Mayer",
    readTime: 14,
    url: "/knowledge/gut-brain-axis",
    publishedAt: new Date("2026-02-09"),
  },
  {
    title: "Circadian Nutrition: When You Eat Matters as Much as What You Eat",
    description: "How meal timing affects insulin sensitivity, gene expression, and circadian clock genes. Time-restricted eating research from the Salk Institute and practical implementation.",
    pillar: "fueling",
    tags: ["Circadian Rhythm", "Fasting", "Metabolism", "Insulin", "Longevity"],
    author: "Dr. Satchin Panda",
    readTime: 15,
    url: "/knowledge/circadian-nutrition",
    publishedAt: new Date("2026-02-13"),
  },
  {
    title: "Muscle-Centric Medicine: Why Skeletal Muscle is the Organ of Longevity",
    description: "How muscle mass is the strongest predictor of all-cause mortality after age 40. Dr. Lyon's framework for protein optimization and resistance training as a longevity strategy.",
    pillar: "fueling",
    tags: ["Protein", "Muscle", "Longevity", "Nutrition", "Aging"],
    author: "Dr. Gabrielle Lyon",
    readTime: 13,
    url: "/knowledge/muscle-centric-medicine",
    publishedAt: new Date("2026-02-17"),
  },
  {
    title: "Fasting Mimicking Diet: Longevity Benefits Without Full Fasting",
    description: "Dr. Valter Longo's research on how a modified 5-day diet can trigger autophagy, stem cell regeneration, and metabolic reset while still consuming food. Protocol details and clinical evidence.",
    pillar: "fueling",
    tags: ["Fasting", "Autophagy", "Longevity", "Nutrition", "Aging"],
    author: "Dr. Valter Longo",
    readTime: 14,
    url: "/knowledge/fasting-mimicking-diet",
    publishedAt: new Date("2026-02-21"),
  },

  // ========== MENTAL PILLAR ==========
  {
    title: "Meditation for Skeptics: Neuroscience-Backed Mindfulness",
    description: "How meditation physically changes your brain, backed by fMRI studies. Practical protocols for beginners including focused attention, open monitoring, and body scan techniques.",
    pillar: "mental",
    tags: ["Meditation", "Mindfulness", "Neuroscience", "Stress", "Mental Health"],
    author: "Dr. Sam Harris",
    readTime: 14,
    url: "/knowledge/meditation-neuroscience",
    publishedAt: new Date("2026-01-22"),
  },
  {
    title: "The Vagus Nerve: Activating Your Body's Calm Response",
    description: "Understanding vagal tone and evidence-based techniques to activate the parasympathetic nervous system. Includes cold exposure, humming, and gargling protocols.",
    pillar: "mental",
    tags: ["Vagus Nerve", "Stress", "ANS", "Breathing", "Recovery"],
    author: "Dr. Stephen Porges",
    readTime: 11,
    url: "/knowledge/vagus-nerve-activation",
    publishedAt: new Date("2026-01-28"),
  },
  {
    title: "Psychedelics and Mental Health: Current Research Status",
    description: "Overview of clinical research on psilocybin, MDMA, and ketamine for depression, PTSD, and anxiety. FDA approval status, clinical trial results, and safety profiles.",
    pillar: "mental",
    tags: ["Psychedelics", "Mental Health", "Research", "Therapy", "Consciousness"],
    author: "Dr. Robin Carhart-Harris",
    readTime: 20,
    url: "/knowledge/psychedelics-mental-health",
    publishedAt: new Date("2026-02-02"),
  },
  {
    title: "The Body Keeps the Score: How Trauma Lives in the Body",
    description: "Understanding how traumatic experiences physically reshape the brain and nervous system. An exploration of EMDR, somatic experiencing, and yoga as evidence-based trauma therapies.",
    pillar: "mental",
    tags: ["Trauma", "Resilience", "Therapy", "Neuroscience", "Recovery"],
    author: "Dr. Bessel van der Kolk",
    readTime: 16,
    url: "/knowledge/trauma-and-the-body",
    publishedAt: new Date("2026-02-06"),
  },
  {
    title: "Dopamine Detox: Resetting Your Reward System",
    description: "Why constant stimulation leads to anhedonia and how periodic abstinence from dopamine-triggering behaviors can restore sensitivity to natural rewards. A clinical approach to digital detox.",
    pillar: "mental",
    tags: ["Dopamine", "Habits", "Mental Health", "Digital Wellness", "Addiction"],
    author: "Dr. Anna Lembke",
    readTime: 12,
    url: "/knowledge/dopamine-detox",
    publishedAt: new Date("2026-02-10"),
  },
  {
    title: "Building Atomic Habits: The 1% Rule for Mental Resilience",
    description: "How small daily habits compound into transformative change. The four laws of behavior change — make it obvious, attractive, easy, and satisfying — applied to mental health and well-being.",
    pillar: "mental",
    tags: ["Habits", "Resilience", "Psychology", "Performance", "Self-Improvement"],
    author: "James Clear",
    readTime: 11,
    url: "/knowledge/atomic-habits-resilience",
    publishedAt: new Date("2026-02-14"),
  },
  {
    title: "Emotional Regulation Through Breathwork: The Physiological Sigh",
    description: "How the double-inhale-exhale pattern (physiological sigh) is the fastest real-time tool for calming the nervous system. Backed by Stanford research on autonomic control.",
    pillar: "mental",
    tags: ["Breathwork", "Stress", "Neuroscience", "Recovery", "ANS"],
    author: "Dr. Andrew Huberman",
    readTime: 9,
    url: "/knowledge/physiological-sigh",
    publishedAt: new Date("2026-02-18"),
  },
  {
    title: "The 40% Rule: David Goggins on Mental Toughness",
    description: "When your mind tells you you're done, you're only 40% done. An exploration of the calloused mind concept and how to build mental endurance through deliberate discomfort.",
    pillar: "mental",
    tags: ["Resilience", "Mental Toughness", "Performance", "Endurance"],
    author: "David Goggins",
    readTime: 10,
    url: "/knowledge/40-percent-rule",
    publishedAt: new Date("2026-02-22"),
  },

  // ========== PHYSICALITY PILLAR ==========
  {
    title: "Zone 2 Training: The Foundation of Metabolic Health",
    description: "Why low-intensity cardio matters more than you think, and how to implement it effectively. Understanding fat oxidation rates, mitochondrial density, and lactate threshold training.",
    pillar: "physicality",
    tags: ["Cardio", "Zone 2", "Mitochondria", "Endurance", "Longevity"],
    author: "Dr. Iñigo San-Millán",
    readTime: 13,
    url: "/knowledge/zone-2-training",
    publishedAt: new Date("2026-01-14"),
  },
  {
    title: "Strength Training for Longevity: Beyond Aesthetics",
    description: "How resistance training affects healthspan, bone density, metabolic health, and longevity. The minimum effective dose for maintaining muscle mass and functional capacity with age.",
    pillar: "physicality",
    tags: ["Strength Training", "Longevity", "Muscle", "Bone Health", "Aging"],
    author: "Dr. Gabrielle Lyon",
    readTime: 15,
    url: "/knowledge/strength-training-longevity",
    publishedAt: new Date("2026-01-27"),
  },
  {
    title: "Movement Variability: Why Gym Bros Need Yoga",
    description: "The case for movement diversity, mobility work, and breaking out of repetitive movement patterns. How functional movement screening reveals hidden imbalances.",
    pillar: "physicality",
    tags: ["Mobility", "Movement", "Flexibility", "Injury Prevention", "Yoga"],
    author: "Kelly Starrett",
    readTime: 10,
    url: "/knowledge/movement-variability",
    publishedAt: new Date("2026-02-04"),
  },
  {
    title: "VO2 Max: The Single Best Predictor of All-Cause Mortality",
    description: "Why cardiorespiratory fitness is the strongest predictor of longevity — stronger than smoking, diabetes, or heart disease. How to test your VO2 max and evidence-based protocols to improve it.",
    pillar: "physicality",
    tags: ["VO2 Max", "Cardio", "Longevity", "Endurance", "Metabolic Health"],
    author: "Dr. Peter Attia",
    readTime: 14,
    url: "/knowledge/vo2-max-mortality",
    publishedAt: new Date("2026-02-08"),
  },
  {
    title: "The Science of Exercise and the Brain: BDNF and Neurogenesis",
    description: "How aerobic exercise triggers brain-derived neurotrophic factor (BDNF) and new neuron growth. The optimal exercise prescriptions for depression, anxiety, ADHD, and cognitive performance.",
    pillar: "physicality",
    tags: ["Brain Health", "Neuroplasticity", "Cardio", "Mental Health", "BDNF"],
    author: "Dr. John Ratey",
    readTime: 13,
    url: "/knowledge/exercise-brain-bdnf",
    publishedAt: new Date("2026-02-12"),
  },
  {
    title: "Born to Run: What Ultramarathoners Teach Us About Human Endurance",
    description: "The evolutionary biology of human running — persistence hunting, the cooling advantage, and why the Tarahumara can run 100+ miles without injury. Lessons for modern runners.",
    pillar: "physicality",
    tags: ["Endurance", "Running", "Evolution", "Performance", "Injury Prevention"],
    author: "Christopher McDougall",
    readTime: 12,
    url: "/knowledge/born-to-run-endurance",
    publishedAt: new Date("2026-02-16"),
  },
  {
    title: "Nasal Breathing for Athletic Performance",
    description: "Why breathing through your nose during exercise improves CO2 tolerance, oxygen delivery, and recovery. The Oxygen Advantage method and practical implementation for athletes.",
    pillar: "physicality",
    tags: ["Breathwork", "Performance", "Endurance", "Recovery", "CO2 Tolerance"],
    author: "Patrick McKeown",
    readTime: 11,
    url: "/knowledge/nasal-breathing-performance",
    publishedAt: new Date("2026-02-20"),
  },

  // ========== FINANCE PILLAR ==========
  {
    title: "The Psychology of Enough: When More Money Stops Mattering",
    description: "Understanding your 'enough' number and the relationship between wealth, happiness, and freedom. How behavioral patterns determine financial success more than intelligence.",
    pillar: "finance",
    tags: ["Psychology of Money", "Financial Independence", "Happiness", "Wealth", "FIRE"],
    author: "Morgan Housel",
    readTime: 12,
    url: "/knowledge/psychology-of-enough",
    publishedAt: new Date("2026-01-16"),
  },
  {
    title: "Bitcoin Standard: Sound Money for Sound Bodies",
    description: "Why Bitcoin's properties align with long-term thinking, low time preference, and health optimization. Understanding fixed supply, proof of work, and monetary sovereignty.",
    pillar: "finance",
    tags: ["Bitcoin", "Sound Money", "Time Preference", "Savings", "Independence"],
    author: "Saifedean Ammous",
    readTime: 18,
    url: "/knowledge/bitcoin-standard-health",
    publishedAt: new Date("2026-01-24"),
  },
  {
    title: "Index Funds and the 4% Rule: Financial Optimization Basics",
    description: "Simple, evidence-based approach to investing and financial independence. How a three-fund portfolio and the 4% safe withdrawal rate can provide lifelong passive income.",
    pillar: "finance",
    tags: ["Investing", "Index Funds", "FIRE", "Passive Income", "Financial Independence"],
    author: "JL Collins",
    readTime: 14,
    url: "/knowledge/index-funds-4-percent-rule",
    publishedAt: new Date("2026-01-31"),
  },
  {
    title: "The FIRE Movement: Financial Independence, Retire Early",
    description: "A comprehensive overview of the FIRE movement — from Lean FIRE to Fat FIRE. Savings rate calculations, the math behind early retirement, and how to balance optimization with living.",
    pillar: "finance",
    tags: ["FIRE", "Financial Independence", "Savings", "Investing", "Frugality"],
    author: "Vicki Robin",
    readTime: 15,
    url: "/knowledge/fire-movement-guide",
    publishedAt: new Date("2026-02-06"),
  },
  {
    title: "Health as Wealth: The ROI of Investing in Your Body",
    description: "Why spending on health optimization — gym memberships, quality food, sleep tech, therapy — delivers the highest return on investment of any expenditure. The hidden cost of poor health.",
    pillar: "finance",
    tags: ["Health ROI", "Investing", "Longevity", "Optimization", "Wealth"],
    author: "Tim Ferriss",
    readTime: 11,
    url: "/knowledge/health-as-wealth",
    publishedAt: new Date("2026-02-10"),
  },
  {
    title: "Automating Your Finances: The Set-It-and-Forget-It System",
    description: "How to build a fully automated financial system that handles bills, savings, investments, and giving without daily decisions. The conscious spending plan and guilt-free spending categories.",
    pillar: "finance",
    tags: ["Automation", "Savings", "Investing", "Financial Independence", "Systems"],
    author: "Ramit Sethi",
    readTime: 13,
    url: "/knowledge/automate-finances",
    publishedAt: new Date("2026-02-14"),
  },
  {
    title: "Geographic Arbitrage: Earn in Dollars, Live Like a King",
    description: "How remote work enables geographic arbitrage — earning in strong currencies while living in lower-cost locations. Tax optimization strategies and lifestyle design for financial freedom.",
    pillar: "finance",
    tags: ["FIRE", "Remote Work", "Tax Optimization", "Lifestyle Design", "Freedom"],
    author: "Kristy Shen & Bryce Leung",
    readTime: 12,
    url: "/knowledge/geographic-arbitrage",
    publishedAt: new Date("2026-02-18"),
  },
  {
    title: "Compound Interest and the Decade Lag: Why Starting Early Matters",
    description: "The mathematics of compounding and why 10 years of investing in your 20s outperforms 30 years in your 40s. Visualizing exponential growth and the cost of delayed action.",
    pillar: "finance",
    tags: ["Compound Interest", "Investing", "Index Funds", "FIRE", "Mathematics"],
    author: "Napoleon Hill",
    readTime: 10,
    url: "/knowledge/compound-interest-decade-lag",
    publishedAt: new Date("2026-02-22"),
  },
]

async function main() {
  console.log('🌱 Seeding knowledge articles...')

  for (const article of knowledgeArticles) {
    const slug = article.title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '')
    const existing = await prisma.article.findUnique({ where: { slug } })
    if (!existing) {
      await prisma.article.create({
        data: {
          ...article,
          id: randomUUID(),
          slug,
          tags: JSON.stringify(article.tags),
          updatedAt: new Date(),
        },
      })
    }
  }

  console.log(`✅ Created ${knowledgeArticles.length} knowledge articles`)
}

main()
  .catch((e) => {
    console.error('❌ Seeding failed:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
