import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const newMarketplaceItems = [
  // COGNITION
  {
    title: "Deep Work Protocol: 4-Hour Focus Sessions",
    description: "Build the capacity for deep, distraction-free work through progressive training and environmental design",
    pillar: "cognition",
    type: "premium",
    author: "Cal Newport",
    rating: 4.8,
    reviews: 312,
    price: 49,
    duration: "6 weeks",
    color: "bg-cognition/10 border-cognition/30 hover:border-cognition/50",
    iconColor: "text-cognition",
  },
  {
    title: "Memory Palace Technique Masterclass",
    description: "Learn ancient memory techniques used by memory champions to remember anything",
    pillar: "cognition",
    type: "premium",
    author: "Joshua Foer",
    rating: 4.6,
    reviews: 189,
    price: 39,
    duration: "4 weeks",
    color: "bg-cognition/10 border-cognition/30 hover:border-cognition/50",
    iconColor: "text-cognition",
  },
  {
    title: "Brain-Derived Neurotrophic Factor (BDNF) Optimization",
    description: "Lifestyle interventions to maximize BDNF for neuroplasticity and cognitive health",
    pillar: "cognition",
    type: "opensource",
    author: "Liberture Community",
    rating: 4.7,
    reviews: 445,
    price: 0,
    duration: "Self-paced",
    color: "bg-cognition/10 border-cognition/30 hover:border-cognition/50",
    iconColor: "text-cognition",
  },
  {
    title: "Caffeine Cycling for Sustained Performance",
    description: "Strategic caffeine use protocol to prevent tolerance and maintain cognitive benefits",
    pillar: "cognition",
    type: "opensource",
    author: "Dr. Matthew Walker",
    rating: 4.5,
    reviews: 567,
    price: 0,
    duration: "Ongoing",
    color: "bg-cognition/10 border-cognition/30 hover:border-cognition/50",
    iconColor: "text-cognition",
  },

  // RECOVERY
  {
    title: "Sleep Optimization: From Average to Elite",
    description: "Complete sleep protocol covering environment, supplements, timing, and tracking",
    pillar: "recovery",
    type: "premium",
    author: "Dr. Andrew Huberman",
    rating: 4.9,
    reviews: 891,
    price: 69,
    duration: "8 weeks",
    color: "bg-recovery/10 border-recovery/30 hover:border-recovery/50",
    iconColor: "text-recovery",
  },
  {
    title: "Contrast Therapy Protocol: Hot & Cold",
    description: "Sauna and cold plunge cycling for recovery, longevity, and resilience",
    pillar: "recovery",
    type: "premium",
    author: "Dr. Rhonda Patrick",
    rating: 4.8,
    reviews: 423,
    price: 59,
    duration: "12 weeks",
    color: "bg-recovery/10 border-recovery/30 hover:border-recovery/50",
    iconColor: "text-recovery",
  },
  {
    title: "HRV-Guided Training: Listen to Your Body",
    description: "Use heart rate variability to optimize training intensity and recovery timing",
    pillar: "recovery",
    type: "opensource",
    author: "Liberture Community",
    rating: 4.6,
    reviews: 678,
    price: 0,
    duration: "Ongoing",
    color: "bg-recovery/10 border-recovery/30 hover:border-recovery/50",
    iconColor: "text-recovery",
  },
  {
    title: "Breathing Techniques for Recovery",
    description: "Box breathing, physiological sighs, and other protocols for parasympathetic activation",
    pillar: "recovery",
    type: "opensource",
    author: "Wim Hof & James Nestor",
    rating: 4.7,
    reviews: 1203,
    price: 0,
    duration: "Self-paced",
    color: "bg-recovery/10 border-recovery/30 hover:border-recovery/50",
    iconColor: "text-recovery",
  },
  {
    title: "Red Light Therapy Home Protocol",
    description: "DIY guide to red and near-infrared light therapy for recovery and skin health",
    pillar: "recovery",
    type: "opensource",
    author: "Ari Whitten",
    rating: 4.4,
    reviews: 334,
    price: 0,
    duration: "Self-paced",
    color: "bg-recovery/10 border-recovery/30 hover:border-recovery/50",
    iconColor: "text-recovery",
  },

  // FUELING
  {
    title: "Carnivore Diet: 90-Day Elimination Protocol",
    description: "Structured approach to the carnivore diet with tracking, troubleshooting, and reintroduction",
    pillar: "fueling",
    type: "premium",
    author: "Dr. Paul Saladino",
    rating: 4.5,
    reviews: 289,
    price: 79,
    duration: "90 days",
    color: "bg-fueling/10 border-fueling/30 hover:border-fueling/50",
    iconColor: "text-fueling",
  },
  {
    title: "Ketogenic Diet Masterclass",
    description: "Complete guide to ketosis: macros, meal plans, troubleshooting, and performance optimization",
    pillar: "fueling",
    type: "premium",
    author: "Dr. Dom D'Agostino",
    rating: 4.7,
    reviews: 567,
    price: 89,
    duration: "12 weeks",
    color: "bg-fueling/10 border-fueling/30 hover:border-fueling/50",
    iconColor: "text-fueling",
  },
  {
    title: "Microbiome Optimization Protocol",
    description: "Evidence-based strategies for gut health through diet, prebiotics, and lifestyle",
    pillar: "fueling",
    type: "premium",
    author: "Dr. Will Bulsiewicz",
    rating: 4.6,
    reviews: 412,
    price: 49,
    duration: "8 weeks",
    color: "bg-fueling/10 border-fueling/30 hover:border-fueling/50",
    iconColor: "text-fueling",
  },
  {
    title: "Insulin Sensitivity Optimization",
    description: "Strategies to improve insulin sensitivity through diet timing, exercise, and supplements",
    pillar: "fueling",
    type: "opensource",
    author: "Dr. Ben Bikman",
    rating: 4.8,
    reviews: 789,
    price: 0,
    duration: "Ongoing",
    color: "bg-fueling/10 border-fueling/30 hover:border-fueling/50",
    iconColor: "text-fueling",
  },
  {
    title: "Meal Timing for Performance",
    description: "When to eat for cognitive performance, training, and sleep quality",
    pillar: "fueling",
    type: "opensource",
    author: "Liberture Community",
    rating: 4.5,
    reviews: 623,
    price: 0,
    duration: "Self-paced",
    color: "bg-fueling/10 border-fueling/30 hover:border-fueling/50",
    iconColor: "text-fueling",
  },

  // MENTAL
  {
    title: "Stoic Philosophy for Modern Life",
    description: "Apply ancient stoic practices to build mental resilience and emotional regulation",
    pillar: "mental",
    type: "premium",
    author: "Ryan Holiday",
    rating: 4.8,
    reviews: 678,
    price: 39,
    duration: "6 weeks",
    color: "bg-mental/10 border-mental/30 hover:border-mental/50",
    iconColor: "text-mental",
  },
  {
    title: "Neurofeedback Training Protocol",
    description: "Learn to control your brainwaves for improved focus, calm, and mental performance",
    pillar: "mental",
    type: "premium",
    author: "Dr. Andrew Hill",
    rating: 4.6,
    reviews: 234,
    price: 149,
    duration: "16 weeks",
    color: "bg-mental/10 border-mental/30 hover:border-mental/50",
    iconColor: "text-mental",
  },
  {
    title: "Anxiety Reduction Toolbox",
    description: "Evidence-based techniques for managing anxiety without medication",
    pillar: "mental",
    type: "opensource",
    author: "Liberture Community",
    rating: 4.7,
    reviews: 1456,
    price: 0,
    duration: "Self-paced",
    color: "bg-mental/10 border-mental/30 hover:border-mental/50",
    iconColor: "text-mental",
  },
  {
    title: "Journaling for Mental Clarity",
    description: "Structured journaling practices for self-awareness, goal-setting, and emotional processing",
    pillar: "mental",
    type: "opensource",
    author: "Tim Ferriss",
    rating: 4.6,
    reviews: 892,
    price: 0,
    duration: "Ongoing",
    color: "bg-mental/10 border-mental/30 hover:border-mental/50",
    iconColor: "text-mental",
  },

  // PHYSICALITY
  {
    title: "Longevity Strength Training Program",
    description: "Age-proof your body with science-backed resistance training for healthspan",
    pillar: "physicality",
    type: "premium",
    author: "Dr. Peter Attia",
    rating: 4.9,
    reviews: 734,
    price: 99,
    duration: "12 weeks",
    color: "bg-physicality/10 border-physicality/30 hover:border-physicality/50",
    iconColor: "text-physicality",
  },
  {
    title: "Mobility Mastery: Complete Joint Health",
    description: "Comprehensive mobility program for pain-free movement and injury prevention",
    pillar: "physicality",
    type: "premium",
    author: "Kelly Starrett",
    rating: 4.7,
    reviews: 567,
    price: 69,
    duration: "10 weeks",
    color: "bg-physicality/10 border-physicality/30 hover:border-physicality/50",
    iconColor: "text-physicality",
  },
  {
    title: "Zone 2 Cardio Foundation",
    description: "Build your aerobic base with low-intensity cardio for metabolic health",
    pillar: "physicality",
    type: "opensource",
    author: "Dr. Iñigo San-Millán",
    rating: 4.8,
    reviews: 945,
    price: 0,
    duration: "Ongoing",
    color: "bg-physicality/10 border-physicality/30 hover:border-physicality/50",
    iconColor: "text-physicality",
  },
  {
    title: "Rucking Protocol for Busy People",
    description: "Build strength and endurance by walking with weight - minimal time, maximum results",
    pillar: "physicality",
    type: "opensource",
    author: "Liberture Community",
    rating: 4.5,
    reviews: 623,
    price: 0,
    duration: "Self-paced",
    color: "bg-physicality/10 border-physicality/30 hover:border-physicality/50",
    iconColor: "text-physicality",
  },
  {
    title: "Functional Movement Screening",
    description: "Identify and fix movement imbalances before they become injuries",
    pillar: "physicality",
    type: "opensource",
    author: "Gray Cook",
    rating: 4.6,
    reviews: 478,
    price: 0,
    duration: "Self-paced",
    color: "bg-physicality/10 border-physicality/30 hover:border-physicality/50",
    iconColor: "text-physicality",
  },

  // FINANCE
  {
    title: "Financial Independence Blueprint",
    description: "Step-by-step guide to achieving financial freedom and early retirement",
    pillar: "finance",
    type: "premium",
    author: "Mr. Money Mustache",
    rating: 4.8,
    reviews: 456,
    price: 59,
    duration: "8 weeks",
    color: "bg-finance/10 border-finance/30 hover:border-finance/50",
    iconColor: "text-finance",
  },
  {
    title: "Bitcoin Self-Custody Masterclass",
    description: "Secure your Bitcoin with multi-sig, hardware wallets, and best practices",
    pillar: "finance",
    type: "premium",
    author: "Jameson Lopp",
    rating: 4.9,
    reviews: 312,
    price: 79,
    duration: "4 weeks",
    color: "bg-finance/10 border-finance/30 hover:border-finance/50",
    iconColor: "text-finance",
  },
  {
    title: "Tax Optimization for High Earners",
    description: "Legal strategies to minimize tax burden and maximize wealth building",
    pillar: "finance",
    type: "premium",
    author: "CPA Community",
    rating: 4.7,
    reviews: 234,
    price: 99,
    duration: "6 weeks",
    color: "bg-finance/10 border-finance/30 hover:border-finance/50",
    iconColor: "text-finance",
  },
  {
    title: "Side Hustle to Full-Time Income",
    description: "Build location-independent income streams aligned with your skills",
    pillar: "finance",
    type: "opensource",
    author: "Liberture Community",
    rating: 4.6,
    reviews: 892,
    price: 0,
    duration: "Self-paced",
    color: "bg-finance/10 border-finance/30 hover:border-finance/50",
    iconColor: "text-finance",
  },
  {
    title: "Minimalist Budget Framework",
    description: "Simple budgeting system focusing on value alignment over restriction",
    pillar: "finance",
    type: "opensource",
    author: "Ramit Sethi",
    rating: 4.5,
    reviews: 1234,
    price: 0,
    duration: "Self-paced",
    color: "bg-finance/10 border-finance/30 hover:border-finance/50",
    iconColor: "text-finance",
  },
]

async function main() {
  console.log('🌱 Adding new marketplace items...')

  for (const item of newMarketplaceItems) {
    await prisma.marketplaceItem.create({
      data: item,
    })
  }

  console.log(`✅ Created ${newMarketplaceItems.length} new marketplace items`)
  
  const total = await prisma.marketplaceItem.count()
  console.log(`📊 Total marketplace items: ${total}`)
}

main()
  .catch((e) => {
    console.error('❌ Seeding failed:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
