import type { Collection } from "../types"

/**
 * Marcus Aurelius, Epictetus and Seneca are all long out of copyright, so these
 * are quoted directly. Translations used are the public-domain ones (Long,
 * Gummere, Higginson), lightly modernised for readability.
 */
export const stoicism: Collection = {
  id: "stoicism",
  name: "Stoicism",
  description:
    "Two thousand years of people working out what is actually theirs to control. Read one, apply it once.",
  pillar: "mind",
  attributionNote: "Public-domain translations. Modernised lightly for readability.",
  quotes: [
    {
      id: "stoicism-control-1",
      kind: "quote",
      collection: "stoicism",
      text: "You have power over your mind — not outside events. Realise this, and you will find strength.",
      author: "Marcus Aurelius",
      source: "Meditations, 12.8",
      application: "Name one thing today that is genuinely outside your control, and stop spending on it.",
    },
    {
      id: "stoicism-control-2",
      kind: "quote",
      collection: "stoicism",
      text: "Some things are within our power, while others are not. Within our power are opinion, motivation, desire, aversion — in short, whatever is of our own doing. Not within our power are our body, our property, reputation, office — whatever is not of our own doing.",
      author: "Epictetus",
      source: "Enchiridion, 1",
      application: "Sort today's worries into the two piles before you act on any of them.",
    },
    {
      id: "stoicism-morning-1",
      kind: "quote",
      collection: "stoicism",
      text: "When you arise in the morning, think of what a precious privilege it is to be alive — to breathe, to think, to enjoy, to love.",
      author: "Marcus Aurelius",
      source: "Meditations",
      application: "Before the first screen of the day, notice that you woke up.",
    },
    {
      id: "stoicism-morning-2",
      kind: "quote",
      collection: "stoicism",
      text: "Begin the morning by saying to yourself: today I shall meet with the busybody, the ungrateful, the arrogant, the deceitful, the envious, the unsocial. All these things happen to them by reason of their ignorance of what is good and evil.",
      author: "Marcus Aurelius",
      source: "Meditations, 2.1",
      application: "Expect the friction. It stops being an ambush.",
    },
    {
      id: "stoicism-obstacle-1",
      kind: "quote",
      collection: "stoicism",
      text: "The impediment to action advances action. What stands in the way becomes the way.",
      author: "Marcus Aurelius",
      source: "Meditations, 5.20",
      application: "Take the thing blocking you today and ask what it is teaching.",
    },
    {
      id: "stoicism-time-1",
      kind: "quote",
      collection: "stoicism",
      text: "It is not that we have a short time to live, but that we waste a great deal of it. Life is long enough, and a sufficiently generous amount has been given to us for the highest achievements if it were all well invested.",
      author: "Seneca",
      source: "On the Shortness of Life, 1",
      pillars: ["work"],
      application: "Audit one hour of today. Was it invested or spent?",
    },
    {
      id: "stoicism-time-2",
      kind: "quote",
      collection: "stoicism",
      text: "Nothing, to my way of thinking, is a better proof of a well-ordered mind than a man's ability to stop just where he is and pass some time in his own company.",
      author: "Seneca",
      source: "Letters, 2",
      pillars: ["mind"],
    },
    {
      id: "stoicism-action-1",
      kind: "quote",
      collection: "stoicism",
      text: "Waste no more time arguing about what a good man should be. Be one.",
      author: "Marcus Aurelius",
      source: "Meditations, 10.16",
      application: "Skip the planning today. Do the smallest version now.",
    },
    {
      id: "stoicism-adversity-1",
      kind: "quote",
      collection: "stoicism",
      text: "Difficulties strengthen the mind, as labour does the body.",
      author: "Seneca",
      source: "Letters",
      pillars: ["exercise", "mind"],
    },
    {
      id: "stoicism-adversity-2",
      kind: "quote",
      collection: "stoicism",
      text: "It is not the man who has too little, but the man who craves more, that is poor.",
      author: "Seneca",
      source: "Letters, 2",
      pillars: ["finance"],
      application: "Before the next purchase, ask whether it's the thing you want or the wanting.",
    },
    {
      id: "stoicism-premeditatio-1",
      kind: "quote",
      collection: "stoicism",
      text: "Nothing happens to the wise man against his expectation. He foresees that something may intervene to prevent what he has planned.",
      author: "Seneca",
      source: "On Tranquility of Mind",
      application: "Premeditatio malorum: name what could go wrong today, then start anyway.",
    },
    {
      id: "stoicism-judgment-1",
      kind: "quote",
      collection: "stoicism",
      text: "Men are disturbed not by the things which happen, but by the opinions about the things.",
      author: "Epictetus",
      source: "Enchiridion, 5",
      application: "Separate what happened from the story you told about it.",
    },
    {
      id: "stoicism-judgment-2",
      kind: "quote",
      collection: "stoicism",
      text: "If you are pained by any external thing, it is not this thing that disturbs you, but your own judgment about it. And it is in your power to wipe out this judgment now.",
      author: "Marcus Aurelius",
      source: "Meditations, 8.47",
    },
    {
      id: "stoicism-evening-1",
      kind: "quote",
      collection: "stoicism",
      text: "I will keep constant watch over myself and — most usefully — will put each day up for review. This is what makes us evil: no one of us looks back over his own life.",
      author: "Seneca",
      source: "On Anger, 3.36",
      application: "Tonight, ask the three questions: what did I do badly, what did I do well, what did I leave undone?",
    },
    {
      id: "stoicism-present-1",
      kind: "quote",
      collection: "stoicism",
      text: "Confine yourself to the present.",
      author: "Marcus Aurelius",
      source: "Meditations, 7.29",
      pillars: ["mind", "work"],
    },
    {
      id: "stoicism-body-1",
      kind: "quote",
      collection: "stoicism",
      text: "It is a disgrace for a man to grow old in careless self-neglect before seeing what manner of man he may become by developing his bodily strength and beauty to their highest limit.",
      author: "Socrates, quoted by Xenophon",
      source: "Memorabilia, 3.12",
      pillars: ["exercise"],
    },
    {
      id: "stoicism-habit-1",
      kind: "quote",
      collection: "stoicism",
      text: "Every habit and capability is confirmed and grows in its corresponding actions: walking by walking, running by running. Therefore, if you want to do something, make a habit of it.",
      author: "Epictetus",
      source: "Discourses, 2.18",
      application: "The habit you repeated today is the one you are becoming. Choose accordingly.",
    },
    {
      id: "stoicism-enough-1",
      kind: "quote",
      collection: "stoicism",
      text: "He who is not satisfied with a little, is satisfied with nothing.",
      author: "Epicurus",
      pillars: ["finance", "nutrition"],
    },
    {
      id: "stoicism-discipline-1",
      kind: "quote",
      collection: "stoicism",
      text: "No man is free who is not master of himself.",
      author: "Epictetus",
    },
    {
      id: "stoicism-sleep-1",
      kind: "quote",
      collection: "stoicism",
      text: "Sleep is a portion of death — take it willingly, and rise as though returning.",
      author: "Seneca",
      source: "Letters, 77 (paraphrase)",
      pillars: ["sleep"],
    },
    {
      id: "stoicism-attention-1",
      kind: "quote",
      collection: "stoicism",
      text: "Very little is needed to make a happy life; it is all within yourself, in your way of thinking.",
      author: "Marcus Aurelius",
      source: "Meditations, 7.67",
    },
    {
      id: "stoicism-comparison-1",
      kind: "quote",
      collection: "stoicism",
      text: "How much time he gains who does not look to see what his neighbour says or does or thinks.",
      author: "Marcus Aurelius",
      source: "Meditations, 4.18",
      pillars: ["work", "finance"],
    },
    {
      id: "stoicism-start-1",
      kind: "quote",
      collection: "stoicism",
      text: "No man ever steps in the same river twice, for it is not the same river and he is not the same man.",
      author: "Heraclitus",
      application: "Yesterday's failed streak belonged to a different person. Start again.",
    },
    {
      id: "stoicism-mortality-1",
      kind: "quote",
      collection: "stoicism",
      text: "You could leave life right now. Let that determine what you do and say and think.",
      author: "Marcus Aurelius",
      source: "Meditations, 2.11",
    },
    {
      id: "stoicism-effort-1",
      kind: "quote",
      collection: "stoicism",
      text: "First say to yourself what you would be; and then do what you have to do.",
      author: "Epictetus",
      source: "Discourses, 3.23",
      application: "Identity first, action second. That order is not accidental.",
    },
  ],
}
